version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install pandas boto3
  build:
    commands:
      - python etl_script.py
